name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    name: ðŸ”Ž Test Solution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: TypeShim.E2E/vitest/package-lock.json

      - name: Restore
        run: >
          dotnet nuget disable source LocalDev &&
          dotnet restore TypeShim.slnx
      - name: Build
        run: >
          dotnet build TypeShim.slnx 
          --configuration Release 
          --no-restore

      - name: Initialize E2E
        working-directory: TypeShim.E2E/vitest
        run: npm run initialize

      - name: Run Unit Tests
        run: >
          dotnet test TypeShim.slnx 
          --configuration Release 
          --no-build 
          --verbosity normal
          --logger "trx;LogFileName=test-results.trx"

      - name: Run E2E (Node)
        if: (!cancelled())
        working-directory: TypeShim.E2E/vitest
        run: npm run test:node

      - name: Run E2E (Browser)
        if: (!cancelled())
        working-directory: TypeShim.E2E/vitest
        run: npm run test:browser

      - name: Publish Test Results
        id: test-results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            **/*.trx
            **/e2e-report-*.xml
      
      - name: Determine badge content
        if: ${{ !cancelled() && github.event_name == 'push' }}
        shell: bash
        run: |
          conclusion='${{ fromJSON(steps.test-results.outputs.json).conclusion }}'
          if [ "$conclusion" = "success" ]; then
            echo "BADGE_COLOR=#26cc23" >> "$GITHUB_ENV"
            echo "BADGE_MESSAGE=${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs_succ }} passing" >> "$GITHUB_ENV"
          else
            echo "BADGE_COLOR=#cc5623" >> "$GITHUB_ENV"
            echo "BADGE_MESSAGE=${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs_fail }}/${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} failing" >> "$GITHUB_ENV"
          fi

      - name: Update badge
        if: ${{ !cancelled() && github.event_name == 'push' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: '0f24ed28316a25f6293d5771a247f19d'
          filename: typeshim-tests-badge.json
          label: Tests
          message: ${{ env.BADGE_MESSAGE }}
          color: ${{ env.BADGE_COLOR }}
